/*****************************************************************************
 * Project: MGMWimpSensitivity                                               *
 *                                                                           *
 * This code was autogenerated by RooClassFactory, and modified by mgmarino  * 
 *****************************************************************************/

/*Pdf according to Lewin/Smith 'Review of mathematics, numerical factors, and corrections for dark matter experiments based on elastic nuclear recoil' eqn. (3.13)
       Rate without escape velocity v_esc, with finite annual modulated velocity v_E of earth*/

/*
 * This class handles the differential rate of a WIMP interaction,
 * including escape velocity.  The formulae are taken from Lewin/Smith
 * (1996)
 */
#ifndef _MGMWimpDiffRateEscapeVelPdf_hh_
#define _MGMWimpDiffRateEscapeVelPdf_hh_

#include "MGMWimpDiffRatePdf.hh"
#include "RooRealProxy.h"
#include "RooAbsReal.h"
 
class MGMWimpDiffRateEscapeVelPdf : public MGMWimpDiffRatePdf {
public:
  MGMWimpDiffRateEscapeVelPdf() {} ; 
  MGMWimpDiffRateEscapeVelPdf(const char *name, const char *title,
	      RooAbsReal& _v_sub_0,       // Base velocity of velocity-distribution
	      RooAbsReal& _v_sub_min,     // Velocity corresponding to minimum energy which can give regoil energy E_R (recoil energy dependent)
	      RooAbsReal& _v_sub_E,       // Earth velocity (with annual modulation)
	      RooAbsReal& _R_sub_0,       // Base rate
	      RooAbsReal& _E_sub_0,       // Lewin/Smith E_0
	      RooAbsReal& _r,             // Lewin/Smith r
	      RooAbsReal& _v_sub_esc,     // Escape velocity
	      MGMVWimpFormFactor& _form_factor = MGMVWimpFormFactor::DefaultFormFactor());  // Form factor != 1 can be included
  MGMWimpDiffRateEscapeVelPdf(const MGMWimpDiffRateEscapeVelPdf& other, const char* name=0) ;        // Constructor for cloning
  virtual TObject* clone(const char* newname) const { return new MGMWimpDiffRateEscapeVelPdf(*this,newname); }      // Cloning with different name
  inline virtual ~MGMWimpDiffRateEscapeVelPdf() { }

protected:

  RooRealProxy v_sub_esc ;

  
  virtual Double_t EvaluatePDF() const ;
  virtual Double_t getK0OverK1() const ;

private:

  ClassDef(MGMWimpDiffRateEscapeVelPdf,1)
};
 
#endif
